// All 300 cards for DUO DÉFI — Culture Générale
// Categories: histoire (90), geographie (60), sciences (60), arts (50), sport (20), joker (20)

export type CardCategory = "histoire" | "geographie" | "sciences" | "arts" | "sport" | "joker";

export interface CardSeed {
  category: CardCategory;
  prompt: string;
  answer?: string;
  points: number;
}

export const CARDS: CardSeed[] = [
  // ============ HISTOIRE 🏛️ (90 cards) — 3 points ============
  { category: "histoire", prompt: "Quelle civilisation a construit la ville de Machu Picchu ?", answer: "Les Incas", points: 3 },
  { category: "histoire", prompt: "Quel peuple a fondé la ville de Carthage ?", answer: "Les Phéniciens", points: 3 },
  { category: "histoire", prompt: "Quelle ancienne civilisation a inventé l'écriture cunéiforme ?", answer: "Les Sumériens", points: 3 },
  { category: "histoire", prompt: "Quelle civilisation mésoaméricaine a prospéré dans la péninsule du Yucatán ?", answer: "Les Mayas", points: 3 },
  { category: "histoire", prompt: "Quel roi babylonien a rédigé un célèbre code de lois vers 1750 av. J.-C. ?", answer: "Hammurabi", points: 3 },
  { category: "histoire", prompt: "Quel roi macédonien conquit la Perse et l'Égypte au IVe siècle av. J.-C. ?", answer: "Alexandre le Grand", points: 3 },
  { category: "histoire", prompt: "Quelle cité-État grecque était réputée pour son système militaire ?", answer: "Sparte", points: 3 },
  { category: "histoire", prompt: "Quel empereur romain a fait construire le Colisée ?", answer: "Vespasien", points: 3 },
  { category: "histoire", prompt: "Quel philosophe grec fut le maître d'Alexandre le Grand ?", answer: "Aristote", points: 3 },
  { category: "histoire", prompt: "Quel empereur romain a promulgué l'édit de Milan en 313 ?", answer: "Constantin Ier", points: 3 },
  { category: "histoire", prompt: "Qui a fondé l'Empire mongol au XIIIe siècle ?", answer: "Gengis Khan", points: 3 },
  { category: "histoire", prompt: "Quel empereur byzantin a codifié le droit romain au VIe siècle ?", answer: "Justinien Ier", points: 3 },
  { category: "histoire", prompt: "Quel empire a eu Constantinople pour capitale après la chute de Rome ?", answer: "L'Empire byzantin", points: 3 },
  { category: "histoire", prompt: "Quel grand empire ouest-africain a eu pour capitale Gao ?", answer: "L'Empire songhaï", points: 3 },
  { category: "histoire", prompt: "Quel roi malien a fait un célèbre pèlerinage à La Mecque au XIVe siècle ?", answer: "Mansa Moussa", points: 3 },
  { category: "histoire", prompt: "Qui était le fondateur de l'Empire du Mali ?", answer: "Soundiata Keïta", points: 3 },
  { category: "histoire", prompt: "Quel est le fondateur de l'Empire ashanti ?", answer: "Osei Tutu Ier", points: 3 },
  { category: "histoire", prompt: "En quelle année l'Empire ottoman a-t-il conquis Constantinople ?", answer: "1453", points: 3 },
  { category: "histoire", prompt: "Quel empire a dirigé l'Inde jusqu'en 1857 avant les Britanniques ?", answer: "L'Empire moghol", points: 3 },
  { category: "histoire", prompt: "Quel roi zoulou a unifié les tribus au début du XIXe siècle ?", answer: "Chaka", points: 3 },
  { category: "histoire", prompt: "En quelle année a débuté la Révolution française ?", answer: "1789", points: 3 },
  { category: "histoire", prompt: "Quel roi de France a été guillotiné en 1793 ?", answer: "Louis XVI", points: 3 },
  { category: "histoire", prompt: "Quelle dynastie a précédé la Révolution française ?", answer: "Les Bourbons", points: 3 },
  { category: "histoire", prompt: "Quel événement a déclenché la Révolution américaine en 1773 ?", answer: "La Boston Tea Party", points: 3 },
  { category: "histoire", prompt: "Quel traité a reconnu l'indépendance des États-Unis en 1783 ?", answer: "Le traité de Paris", points: 3 },
  { category: "histoire", prompt: "Qui a dirigé la Révolution russe de 1917 ?", answer: "Lénine", points: 3 },
  { category: "histoire", prompt: "Qui fut le dernier tsar de Russie ?", answer: "Nicolas II", points: 3 },
  { category: "histoire", prompt: "En quelle année la Révolution haïtienne a-t-elle abouti à l'indépendance ?", answer: "1804", points: 3 },
  { category: "histoire", prompt: "En quelle année a débuté la Première Guerre mondiale ?", answer: "1914", points: 3 },
  { category: "histoire", prompt: "Quel événement a déclenché la Première Guerre mondiale ?", answer: "L'assassinat de l'archiduc François-Ferdinand", points: 3 },
  { category: "histoire", prompt: "Quel traité a mis fin à la Première Guerre mondiale en 1919 ?", answer: "Le traité de Versailles", points: 3 },
  { category: "histoire", prompt: "Quelle bataille de 1916 est restée symbole de la guerre de position ?", answer: "La bataille de Verdun", points: 3 },
  { category: "histoire", prompt: "Quelle année marque la fin de la Seconde Guerre mondiale en Europe ?", answer: "1945", points: 3 },
  { category: "histoire", prompt: "Qui a fondé la France Libre pendant la Seconde Guerre mondiale ?", answer: "Charles de Gaulle", points: 3 },
  { category: "histoire", prompt: "Qui a dirigé l'URSS pendant la Seconde Guerre mondiale ?", answer: "Joseph Staline", points: 3 },
  { category: "histoire", prompt: "Qui a été le premier ministre britannique pendant la majeure partie de la Seconde Guerre mondiale ?", answer: "Winston Churchill", points: 3 },
  { category: "histoire", prompt: "Sur quelle ville japonaise la première bombe atomique a-t-elle été larguée ?", answer: "Hiroshima", points: 3 },
  { category: "histoire", prompt: "Quelle bataille de 1942-1943 marqua le tournant de la Seconde Guerre mondiale sur le front de l'Est ?", answer: "La bataille de Stalingrad", points: 3 },
  { category: "histoire", prompt: "Qui a découvert la route maritime vers l'Inde en contournant l'Afrique ?", answer: "Vasco de Gama", points: 3 },
  { category: "histoire", prompt: "En quelle année Christophe Colomb a-t-il atteint les Amériques ?", answer: "1492", points: 3 },
  { category: "histoire", prompt: "Quel explorateur a lancé la première expédition ayant fait le tour du monde ?", answer: "Fernand de Magellan", points: 3 },
  { category: "histoire", prompt: "Quel navigateur chinois du XVe siècle mena sept grandes expéditions dans l'océan Indien ?", answer: "Zheng He", points: 3 },
  { category: "histoire", prompt: "Quel explorateur portugais a atteint le cap de Bonne-Espérance en 1488 ?", answer: "Bartolomeu Dias", points: 3 },
  { category: "histoire", prompt: "Qui était le premier président des États-Unis ?", answer: "George Washington", points: 3 },
  { category: "histoire", prompt: "Quel président américain a aboli l'esclavage en 1863 ?", answer: "Abraham Lincoln", points: 3 },
  { category: "histoire", prompt: "Quelle guerre opposa le Nord et le Sud des États-Unis de 1861 à 1865 ?", answer: "La guerre de Sécession", points: 3 },
  { category: "histoire", prompt: "Quel président américain a démissionné à la suite du scandale du Watergate ?", answer: "Richard Nixon", points: 3 },
  { category: "histoire", prompt: "Qui a été le premier président noir des États-Unis ?", answer: "Barack Obama", points: 3 },
  { category: "histoire", prompt: "Qui était le leader du mouvement des droits civiques aux États-Unis, assassiné en 1968 ?", answer: "Martin Luther King Jr.", points: 3 },
  { category: "histoire", prompt: "Qui a été le premier président de l'Afrique du Sud élu au suffrage universel ?", answer: "Nelson Mandela", points: 3 },
  { category: "histoire", prompt: "Quel président sud-africain a libéré Mandela en 1990 ?", answer: "F. W. de Klerk", points: 3 },
  { category: "histoire", prompt: "Qui fut le premier président du Ghana indépendant ?", answer: "Kwame Nkrumah", points: 3 },
  { category: "histoire", prompt: "Quel dirigeant congolais fut assassiné en 1961 ?", answer: "Patrice Lumumba", points: 3 },
  { category: "histoire", prompt: "Qui a proclamé l'indépendance d'Haïti en 1804 ?", answer: "Jean-Jacques Dessalines", points: 3 },
  { category: "histoire", prompt: "Quel empereur français a été exilé à Sainte-Hélène ?", answer: "Napoléon Ier", points: 3 },
  { category: "histoire", prompt: "Quel président français a fondé la Ve République en 1958 ?", answer: "Charles de Gaulle", points: 3 },
  { category: "histoire", prompt: "Qui a proclamé la République turque en 1923 ?", answer: "Mustafa Kemal Atatürk", points: 3 },
  { category: "histoire", prompt: "Quel président américain a lancé le New Deal dans les années 1930 ?", answer: "Franklin D. Roosevelt", points: 3 },
  { category: "histoire", prompt: "Quel pays a colonisé le Brésil ?", answer: "Le Portugal", points: 3 },
  { category: "histoire", prompt: "En quelle année l'Algérie a-t-elle obtenu son indépendance ?", answer: "1962", points: 3 },
  { category: "histoire", prompt: "En quelle année le Sénégal a-t-il obtenu son indépendance ?", answer: "1960", points: 3 },
  { category: "histoire", prompt: "En quelle année le Cameroun a-t-il obtenu son indépendance ?", answer: "1960", points: 3 },
  { category: "histoire", prompt: "En quelle année le Kenya a-t-il obtenu son indépendance ?", answer: "1963", points: 3 },
  { category: "histoire", prompt: "En quelle année l'Inde a-t-elle obtenu son indépendance ?", answer: "1947", points: 3 },
  { category: "histoire", prompt: "Quel pays africain a été fondé par d'anciens esclaves américains en 1847 ?", answer: "Le Libéria", points: 3 },
  { category: "histoire", prompt: "Quel État africain a résisté à la colonisation italienne à la bataille d'Adoua en 1896 ?", answer: "L'Éthiopie", points: 3 },
  { category: "histoire", prompt: "Quel pays a accueilli la Conférence de Berlin en 1884-1885 ?", answer: "L'Allemagne", points: 3 },
  { category: "histoire", prompt: "En quelle année le Tchad a-t-il obtenu son indépendance ?", answer: "1960", points: 3 },
  { category: "histoire", prompt: "Quelle année a vu la crise des missiles à Cuba ?", answer: "1962", points: 3 },
  { category: "histoire", prompt: "Quel dirigeant cubain a pris le pouvoir en 1959 ?", answer: "Fidel Castro", points: 3 },
  { category: "histoire", prompt: "Qui a dirigé la Chine lors de la Révolution culturelle ?", answer: "Mao Zedong", points: 3 },
  { category: "histoire", prompt: "En quelle année la chute du mur de Berlin a-t-elle eu lieu ?", answer: "1989", points: 3 },
  { category: "histoire", prompt: "Quel dirigeant soviétique a lancé la glasnost et la perestroïka ?", answer: "Mikhaïl Gorbatchev", points: 3 },
  { category: "histoire", prompt: "En quelle année l'URSS a-t-elle envoyé le premier homme dans l'espace ?", answer: "1961", points: 3 },
  { category: "histoire", prompt: "En quelle année a eu lieu la bataille de Waterloo ?", answer: "1815", points: 3 },
  { category: "histoire", prompt: "En quelle année a été signée la Magna Carta ?", answer: "1215", points: 3 },
  { category: "histoire", prompt: "Quel traité de 1648 a mis fin à la guerre de Trente Ans ?", answer: "Les traités de Westphalie", points: 3 },
  { category: "histoire", prompt: "Quelle bataille de 732 arrêta l'avancée arabe en Gaule ?", answer: "La bataille de Poitiers", points: 3 },
  { category: "histoire", prompt: "Quel siècle a vu naître la Renaissance italienne ?", answer: "Le XVe siècle", points: 3 },
  { category: "histoire", prompt: "Quelle reine britannique a régné 63 ans au XIXe siècle ?", answer: "La reine Victoria", points: 3 },
  { category: "histoire", prompt: "Qui a mené l'Inde à l'indépendance par la non-violence ?", answer: "Mahatma Gandhi", points: 3 },
  { category: "histoire", prompt: "En quelle année la Chine est-elle devenue une république ?", answer: "1912", points: 3 },
  { category: "histoire", prompt: "En quelle année a été créée l'Organisation des Nations Unies ?", answer: "1945", points: 3 },
  { category: "histoire", prompt: "Quelle conférence de 1945 a fondé l'ONU ?", answer: "La conférence de San Francisco", points: 3 },
  { category: "histoire", prompt: "Quel pays fut le premier à accorder le droit de vote aux femmes au niveau national ?", answer: "La Nouvelle-Zélande", points: 3 },
  { category: "histoire", prompt: "Qui fut la première femme élue chef d'État au monde ?", answer: "Vigdís Finnbogadóttir", points: 3 },
  { category: "histoire", prompt: "Quel régime politique est dirigé par un roi ou une reine ?", answer: "La monarchie", points: 3 },
  { category: "histoire", prompt: "Quelle institution européenne siège à Strasbourg et regroupe des députés élus ?", answer: "Le Parlement européen", points: 3 },
  { category: "histoire", prompt: "Quelle organisation panafricaine a été créée en 2002 ?", answer: "L'Union africaine", points: 3 },
  { category: "histoire", prompt: "Quel système politique repose sur la séparation des pouvoirs exécutif, législatif et judiciaire ?", answer: "La démocratie", points: 3 },

  // ============ GÉOGRAPHIE 🌍 (60 cards) — 2 points ============
  { category: "geographie", prompt: "Quelle est la capitale de l'Australie ?", answer: "Canberra", points: 2 },
  { category: "geographie", prompt: "Quelle est la capitale du Brésil ?", answer: "Brasília", points: 2 },
  { category: "geographie", prompt: "Quelle est la capitale de la Turquie ?", answer: "Ankara", points: 2 },
  { category: "geographie", prompt: "Quelle est la capitale du Canada ?", answer: "Ottawa", points: 2 },
  { category: "geographie", prompt: "Quelle est la capitale de la Suisse ?", answer: "Berne", points: 2 },
  { category: "geographie", prompt: "Quelle est la capitale du Maroc ?", answer: "Rabat", points: 2 },
  { category: "geographie", prompt: "Quelle est la capitale de la Namibie ?", answer: "Windhoek", points: 2 },
  { category: "geographie", prompt: "Quel est le plus long fleuve d'Afrique ?", answer: "Le Nil", points: 2 },
  { category: "geographie", prompt: "Quel fleuve traverse Londres ?", answer: "La Tamise", points: 2 },
  { category: "geographie", prompt: "Quel fleuve traverse Paris ?", answer: "La Seine", points: 2 },
  { category: "geographie", prompt: "Quel fleuve traverse Rome ?", answer: "Le Tibre", points: 2 },
  { category: "geographie", prompt: "Quel est le plus grand fleuve d'Amérique du Sud par son débit ?", answer: "L'Amazone", points: 2 },
  { category: "geographie", prompt: "Quel fleuve traverse Budapest ?", answer: "Le Danube", points: 2 },
  { category: "geographie", prompt: "Quel fleuve traverse le Grand Canyon aux États-Unis ?", answer: "Le Colorado", points: 2 },
  { category: "geographie", prompt: "Quel fleuve traverse Bamako ?", answer: "Le Niger", points: 2 },
  { category: "geographie", prompt: "Quel est le plus haut sommet d'Afrique ?", answer: "Le Kilimandjaro", points: 2 },
  { category: "geographie", prompt: "Quel est le plus haut sommet du monde ?", answer: "L'Everest", points: 2 },
  { category: "geographie", prompt: "Quelle chaîne sépare la France de l'Espagne ?", answer: "Les Pyrénées", points: 2 },
  { category: "geographie", prompt: "Quel est le plus haut sommet d'Europe occidentale ?", answer: "Le mont Blanc", points: 2 },
  { category: "geographie", prompt: "Quelle chaîne de montagnes traverse l'Amérique du Sud sur toute sa côte ouest ?", answer: "La cordillère des Andes", points: 2 },
  { category: "geographie", prompt: "Quel est le plus haut sommet d'Amérique du Nord ?", answer: "Le mont Denali", points: 2 },
  { category: "geographie", prompt: "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?", answer: "L'Oural", points: 2 },
  { category: "geographie", prompt: "Quelle est la plus grande mer fermée du monde ?", answer: "La mer Caspienne", points: 2 },
  { category: "geographie", prompt: "Dans quel océan se trouve Madagascar ?", answer: "L'océan Indien", points: 2 },
  { category: "geographie", prompt: "Quel est le plus grand lac d'Afrique ?", answer: "Le lac Victoria", points: 2 },
  { category: "geographie", prompt: "Quel est le lac le plus profond du monde ?", answer: "Le lac Baïkal", points: 2 },
  { category: "geographie", prompt: "Quelle mer sépare l'Europe de l'Afrique ?", answer: "La mer Méditerranée", points: 2 },
  { category: "geographie", prompt: "Quel est le plus grand océan du monde ?", answer: "L'océan Pacifique", points: 2 },
  { category: "geographie", prompt: "Quel canal relie l'océan Atlantique à l'océan Pacifique ?", answer: "Le canal de Panama", points: 2 },
  { category: "geographie", prompt: "Quel canal relie la mer Méditerranée à la mer Rouge ?", answer: "Le canal de Suez", points: 2 },
  { category: "geographie", prompt: "Quel est le plus grand désert chaud du monde ?", answer: "Le Sahara", points: 2 },
  { category: "geographie", prompt: "Quel est le désert le plus froid du monde ?", answer: "L'Antarctique", points: 2 },
  { category: "geographie", prompt: "Quel désert couvre une grande partie du nord de la Chine et de la Mongolie ?", answer: "Le désert de Gobi", points: 2 },
  { category: "geographie", prompt: "Quel désert borde la côte ouest de l'Amérique du Sud au Chili ?", answer: "Le désert d'Atacama", points: 2 },
  { category: "geographie", prompt: "Quel désert semi-aride couvre une grande partie du Botswana ?", answer: "Le désert du Kalahari", points: 2 },
  { category: "geographie", prompt: "Quel est le plus grand archipel du monde ?", answer: "L'Indonésie", points: 2 },
  { category: "geographie", prompt: "Quelle est la plus grande île du monde ?", answer: "Le Groenland", points: 2 },
  { category: "geographie", prompt: "Quelle île de l'océan Indien est surnommée l'Île Rouge ?", answer: "Madagascar", points: 2 },
  { category: "geographie", prompt: "Quel État insulaire se trouve au sud de l'Inde ?", answer: "Le Sri Lanka", points: 2 },
  { category: "geographie", prompt: "Quelles îles de l'Équateur sont célèbres pour les études de Darwin ?", answer: "Les îles Galápagos", points: 2 },
  { category: "geographie", prompt: "Quel pays partage la plus longue frontière avec les États-Unis ?", answer: "Le Canada", points: 2 },
  { category: "geographie", prompt: "Quel pays partage la frontière terrestre la plus longue avec la France ?", answer: "Le Brésil", points: 2 },
  { category: "geographie", prompt: "Quel bras de mer sépare la Grande-Bretagne de la France ?", answer: "La Manche", points: 2 },
  { category: "geographie", prompt: "Quelle est la monnaie du Japon ?", answer: "Le yen", points: 2 },
  { category: "geographie", prompt: "Quelle est la monnaie du Royaume-Uni ?", answer: "La livre sterling", points: 2 },
  { category: "geographie", prompt: "Quelle est la monnaie officielle de la zone euro ?", answer: "L'euro", points: 2 },
  { category: "geographie", prompt: "Quelle est la monnaie de la Suisse ?", answer: "Le franc suisse", points: 2 },
  { category: "geographie", prompt: "Quelle est la langue officielle du Brésil ?", answer: "Le portugais", points: 2 },
  { category: "geographie", prompt: "Quelle langue bantoue sert de langue véhiculaire en Afrique de l'Est ?", answer: "Le swahili", points: 2 },
  { category: "geographie", prompt: "Quel pays africain a la plus grande population ?", answer: "Le Nigeria", points: 2 },
  { category: "geographie", prompt: "Quel détroit sépare la Sicile de l'Afrique ?", answer: "Le canal de Sicile", points: 2 },
  { category: "geographie", prompt: "Quel volcan actif se trouve en RD Congo dans le parc des Virunga ?", answer: "Le Nyiragongo", points: 2 },
  { category: "geographie", prompt: "Quel détroit sépare l'Afrique de l'Europe ?", answer: "Le détroit de Gibraltar", points: 2 },
  { category: "geographie", prompt: "Quel cap marque l'extrémité sud de l'Afrique ?", answer: "Le cap de Bonne-Espérance", points: 2 },
  { category: "geographie", prompt: "Quel fleuve se jette dans la mer du Nord après avoir traversé l'Allemagne et les Pays-Bas ?", answer: "Le Rhin", points: 2 },
  { category: "geographie", prompt: "Quel est le plus petit pays du monde ?", answer: "Le Vatican", points: 2 },
  { category: "geographie", prompt: "Quel est le plus grand pays du monde par sa superficie ?", answer: "La Russie", points: 2 },
  { category: "geographie", prompt: "Quel pays d'Afrique a la plus grande superficie ?", answer: "L'Algérie", points: 2 },
  { category: "geographie", prompt: "Quel grand pays d'Afrique centrale est traversé par le fleuve Congo ?", answer: "La République démocratique du Congo", points: 2 },
  { category: "geographie", prompt: "Quel pays d'Amérique du Sud a la plus grande superficie ?", answer: "Le Brésil", points: 2 },

  // ============ SCIENCES 🔬 (60 cards) — 3 points (some 4-5) ============
  { category: "sciences", prompt: "Quelle planète est la plus éloignée du Soleil ?", answer: "Neptune", points: 3 },
  { category: "sciences", prompt: "Quelle est la plus grande planète du système solaire ?", answer: "Jupiter", points: 3 },
  { category: "sciences", prompt: "Quelle étoile est au centre de notre système solaire ?", answer: "Le Soleil", points: 3 },
  { category: "sciences", prompt: "Quelle planète est surnommée la planète rouge ?", answer: "Mars", points: 3 },
  { category: "sciences", prompt: "Quelle galaxie abrite notre système solaire ?", answer: "La Voie lactée", points: 3 },
  { category: "sciences", prompt: "Qui fut le premier homme à marcher sur la Lune en 1969 ?", answer: "Neil Armstrong", points: 3 },
  { category: "sciences", prompt: "Combien de planètes compte le système solaire ?", answer: "Huit", points: 3 },
  { category: "sciences", prompt: "Quelle planète possède les anneaux les plus visibles ?", answer: "Saturne", points: 3 },
  { category: "sciences", prompt: "Quel est le satellite naturel de la Terre ?", answer: "La Lune", points: 3 },
  { category: "sciences", prompt: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", answer: "Environ 8 minutes", points: 4 },
  { category: "sciences", prompt: "Quel organe pompe le sang dans le corps humain ?", answer: "Le cœur", points: 3 },
  { category: "sciences", prompt: "Combien d'os possède le corps humain adulte ?", answer: "206", points: 3 },
  { category: "sciences", prompt: "Quel est l'organe le plus volumineux du corps humain ?", answer: "La peau", points: 3 },
  { category: "sciences", prompt: "Quel est le groupe sanguin universel donneur ?", answer: "Le groupe O négatif", points: 3 },
  { category: "sciences", prompt: "Combien de chromosomes possède l'être humain ?", answer: "46", points: 3 },
  { category: "sciences", prompt: "Quel organe filtre le sang et produit l'urine ?", answer: "Les reins", points: 3 },
  { category: "sciences", prompt: "Comment s'appellent les cellules qui défendent l'organisme contre les infections ?", answer: "Les globules blancs", points: 3 },
  { category: "sciences", prompt: "Quelle partie du cerveau régule l'équilibre et la coordination ?", answer: "Le cervelet", points: 4 },
  { category: "sciences", prompt: "Quel est le plus gros organe interne du corps humain ?", answer: "Le foie", points: 3 },
  { category: "sciences", prompt: "Quelle vitamine est synthétisée par la peau sous l'effet du soleil ?", answer: "La vitamine D", points: 3 },
  { category: "sciences", prompt: "Quel est le plus grand mammifère du monde ?", answer: "La baleine bleue", points: 3 },
  { category: "sciences", prompt: "Combien de pattes possède une araignée ?", answer: "Huit", points: 3 },
  { category: "sciences", prompt: "Quel est le seul mammifère capable de voler ?", answer: "La chauve-souris", points: 3 },
  { category: "sciences", prompt: "Quel animal est surnommé le roi de la jungle ?", answer: "Le lion", points: 3 },
  { category: "sciences", prompt: "Combien de cœurs possède un poulpe ?", answer: "Trois", points: 3 },
  { category: "sciences", prompt: "Quel est l'animal terrestre le plus rapide ?", answer: "Le guépard", points: 3 },
  { category: "sciences", prompt: "Combien de chromosomes possède un chimpanzé ?", answer: "48", points: 5 },
  { category: "sciences", prompt: "Combien de chromosomes possède un chien ?", answer: "78", points: 5 },
  { category: "sciences", prompt: "Quelle est l'espèce de grand singe la plus proche de l'humain génétiquement ?", answer: "Le chimpanzé", points: 3 },
  { category: "sciences", prompt: "Quelle est la formule de la relativité restreinte d'Einstein ?", answer: "E=mc²", points: 3 },
  { category: "sciences", prompt: "Quelle est l'unité de mesure de la force ?", answer: "Le newton", points: 3 },
  { category: "sciences", prompt: "Quelle est la vitesse de la lumière dans le vide ?", answer: "Environ 300 000 km/s", points: 3 },
  { category: "sciences", prompt: "Qui a formulé la loi de la gravitation universelle ?", answer: "Isaac Newton", points: 3 },
  { category: "sciences", prompt: "Quelle est la particule chargée négativement dans un atome ?", answer: "L'électron", points: 3 },
  { category: "sciences", prompt: "Quelle est l'unité de mesure de l'intensité électrique ?", answer: "L'ampère", points: 3 },
  { category: "sciences", prompt: "Quel physicien a proposé la théorie de la relativité ?", answer: "Albert Einstein", points: 3 },
  { category: "sciences", prompt: "Quel est le symbole chimique de l'or ?", answer: "Au", points: 3 },
  { category: "sciences", prompt: "Quel est le symbole chimique de l'eau ?", answer: "H₂O", points: 3 },
  { category: "sciences", prompt: "Quel est l'élément le plus abondant dans l'univers ?", answer: "L'hydrogène", points: 3 },
  { category: "sciences", prompt: "Quel gaz constitue la majeure partie de l'atmosphère terrestre ?", answer: "L'azote", points: 3 },
  { category: "sciences", prompt: "Combien d'éléments compte le tableau périodique actuel ?", answer: "118", points: 4 },
  { category: "sciences", prompt: "Quel est le métal le plus conducteur d'électricité ?", answer: "L'argent", points: 3 },
  { category: "sciences", prompt: "Quelle est la formule chimique du sel de table ?", answer: "NaCl", points: 3 },
  { category: "sciences", prompt: "Quel élément a pour symbole Fe ?", answer: "Le fer", points: 3 },
  { category: "sciences", prompt: "Quelle est la valeur approchée du nombre pi ?", answer: "3,14", points: 3 },
  { category: "sciences", prompt: "Comment appelle-t-on un triangle ayant deux côtés égaux ?", answer: "Un triangle isocèle", points: 3 },
  { category: "sciences", prompt: "Combien de côtés possède un hexagone ?", answer: "Six", points: 3 },
  { category: "sciences", prompt: "Quel est le seul nombre premier pair ?", answer: "Le nombre 2", points: 3 },
  { category: "sciences", prompt: "Combien font 12 × 12 ?", answer: "144", points: 3 },
  { category: "sciences", prompt: "Comment s'appelle le théorème reliant les côtés d'un triangle rectangle ?", answer: "Le théorème de Pythagore", points: 3 },
  { category: "sciences", prompt: "Qui a inventé le téléphone ?", answer: "Alexander Graham Bell", points: 3 },
  { category: "sciences", prompt: "Qui a inventé l'ampoule électrique à filament commercialisable ?", answer: "Thomas Edison", points: 3 },
  { category: "sciences", prompt: "Que signifie l'acronyme CPU en informatique ?", answer: "Central Processing Unit", points: 4 },
  { category: "sciences", prompt: "Que signifie l'acronyme HTML ?", answer: "HyperText Markup Language", points: 4 },
  { category: "sciences", prompt: "Qui a mis au point le vaccin contre la rage ?", answer: "Louis Pasteur", points: 3 },
  { category: "sciences", prompt: "Qui a découvert la pénicilline ?", answer: "Alexander Fleming", points: 3 },
  { category: "sciences", prompt: "Quels frères américains ont réalisé le premier vol motorisé en 1903 ?", answer: "Les frères Wright", points: 3 },
  { category: "sciences", prompt: "Quelle est la cause principale des marées ?", answer: "L'attraction de la Lune", points: 3 },
  { category: "sciences", prompt: "Comment s'appelle le processus par lequel les plantes transforment la lumière en énergie ?", answer: "La photosynthèse", points: 3 },
  { category: "sciences", prompt: "Quelle scientifique a reçu deux prix Nobel dans deux disciplines différentes ?", answer: "Marie Curie", points: 4 },

  // ============ ARTS 🎭 (50 cards) — 2 points ============
  { category: "arts", prompt: "Qui a peint La Joconde ?", answer: "Léonard de Vinci", points: 2 },
  { category: "arts", prompt: "Qui a peint Les Nymphéas ?", answer: "Claude Monet", points: 2 },
  { category: "arts", prompt: "Qui a peint La Nuit étoilée ?", answer: "Vincent van Gogh", points: 2 },
  { category: "arts", prompt: "Qui a peint Le Radeau de la Méduse ?", answer: "Théodore Géricault", points: 2 },
  { category: "arts", prompt: "Qui a peint Guernica ?", answer: "Pablo Picasso", points: 2 },
  { category: "arts", prompt: "Quel mouvement artistique Salvador Dalí a-t-il incarné ?", answer: "Le surréalisme", points: 2 },
  { category: "arts", prompt: "Qui a peint La Jeune Fille à la perle ?", answer: "Johannes Vermeer", points: 2 },
  { category: "arts", prompt: "Quelle peintre mexicaine est connue pour ses autoportraits et son sourcil uni ?", answer: "Frida Kahlo", points: 2 },
  { category: "arts", prompt: "Qui a écrit Les Misérables ?", answer: "Victor Hugo", points: 2 },
  { category: "arts", prompt: "Qui a écrit Le Petit Prince ?", answer: "Antoine de Saint-Exupéry", points: 2 },
  { category: "arts", prompt: "Qui a écrit Cent ans de solitude ?", answer: "Gabriel García Márquez", points: 2 },
  { category: "arts", prompt: "Qui a écrit L'Étranger ?", answer: "Albert Camus", points: 2 },
  { category: "arts", prompt: "Qui a écrit Le Vieil Homme et la Mer ?", answer: "Ernest Hemingway", points: 2 },
  { category: "arts", prompt: "Qui a écrit Les Fleurs du mal ?", answer: "Charles Baudelaire", points: 2 },
  { category: "arts", prompt: "Qui a écrit Le Monde s'effondre (Things Fall Apart) ?", answer: "Chinua Achebe", points: 2 },
  { category: "arts", prompt: "Qui a écrit Roméo et Juliette ?", answer: "William Shakespeare", points: 2 },
  { category: "arts", prompt: "Qui a écrit Le Misanthrope ?", answer: "Molière", points: 2 },
  { category: "arts", prompt: "Qui a écrit la tragédie Antigone ?", answer: "Sophocle", points: 2 },
  { category: "arts", prompt: "Qui a écrit En attendant Godot ?", answer: "Samuel Beckett", points: 2 },
  { category: "arts", prompt: "Qui a écrit Le Cid ?", answer: "Pierre Corneille", points: 2 },
  { category: "arts", prompt: "Qui a écrit la tragédie Phèdre ?", answer: "Jean Racine", points: 2 },
  { category: "arts", prompt: "Qui a réalisé le film Citizen Kane ?", answer: "Orson Welles", points: 2 },
  { category: "arts", prompt: "Qui a réalisé Psychose ?", answer: "Alfred Hitchcock", points: 2 },
  { category: "arts", prompt: "Quel film de James Cameron sorti en 1997 a battu tous les records du box-office ?", answer: "Titanic", points: 2 },
  { category: "arts", prompt: "Qui a réalisé Le Parrain ?", answer: "Francis Ford Coppola", points: 2 },
  { category: "arts", prompt: "Quel cinéaste japonais a réalisé Les Sept Samouraïs ?", answer: "Akira Kurosawa", points: 2 },
  { category: "arts", prompt: "Quel réalisateur français a dirigé Jean-Paul Belmondo dans À bout de souffle ?", answer: "Jean-Luc Godard", points: 2 },
  { category: "arts", prompt: "Qui a réalisé Le Dictateur ?", answer: "Charlie Chaplin", points: 2 },
  { category: "arts", prompt: "Quel réalisateur sénégalais a tourné Black Girl en 1966 ?", answer: "Ousmane Sembène", points: 2 },
  { category: "arts", prompt: "Qui a composé La Neuvième Symphonie ?", answer: "Ludwig van Beethoven", points: 2 },
  { category: "arts", prompt: "Qui a composé Le Lac des cygnes ?", answer: "Piotr Ilitch Tchaïkovski", points: 2 },
  { category: "arts", prompt: "Qui a composé l'oratorio Le Messie ?", answer: "Georg Friedrich Haendel", points: 2 },
  { category: "arts", prompt: "Combien de cordes possède un violon ?", answer: "Quatre", points: 2 },
  { category: "arts", prompt: "Quel genre musical est né en Jamaïque dans les années 1960 ?", answer: "Le reggae", points: 2 },
  { category: "arts", prompt: "Quel chanteur jamaïcain a popularisé le reggae dans le monde entier ?", answer: "Bob Marley", points: 2 },
  { category: "arts", prompt: "Qui a composé l'opéra La Flûte enchantée ?", answer: "Wolfgang Amadeus Mozart", points: 2 },
  { category: "arts", prompt: "Quelle cathédrale parisienne est célèbre pour ses arcs-boutants et sa rosace ?", answer: "Notre-Dame de Paris", points: 2 },
  { category: "arts", prompt: "Quel monument parisien a été construit pour l'Exposition universelle de 1889 ?", answer: "La tour Eiffel", points: 2 },
  { category: "arts", prompt: "Quel célèbre monument indien fut érigé en mémoire de l'épouse d'un empereur moghol ?", answer: "Le Taj Mahal", points: 2 },
  { category: "arts", prompt: "Quel amphithéâtre romain pouvait accueillir jusqu'à 50 000 spectateurs ?", answer: "Le Colisée", points: 2 },
  { category: "arts", prompt: "Quel style architectural se caractérise par des arcs en ogive et des vitraux ?", answer: "Le style gothique", points: 2 },
  { category: "arts", prompt: "Quelle statue située à New York a été offerte par la France en 1886 ?", answer: "La statue de la Liberté", points: 2 },
  { category: "arts", prompt: "Quel architecte catalan a conçu la Sagrada Família ?", answer: "Antoni Gaudí", points: 2 },
  { category: "arts", prompt: "Quelle danse traditionnelle argentine est née à Buenos Aires ?", answer: "Le tango", points: 2 },
  { category: "arts", prompt: "Quel mouvement artistique français du XIXe siècle a peint la vie moderne en plein air ?", answer: "L'impressionnisme", points: 2 },
  { category: "arts", prompt: "Quelle salle d'opéra est située place de la Bastille à Paris ?", answer: "L'Opéra Bastille", points: 2 },
  { category: "arts", prompt: "Quel sculpteur français a créé Le Penseur ?", answer: "Auguste Rodin", points: 2 },
  { category: "arts", prompt: "Quelle institution culturelle parisienne est surnommée Beaubourg ?", answer: "Le Centre Pompidou", points: 2 },
  { category: "arts", prompt: "Quel instrument à cordes est joué avec un archet et compte parmi les plus graves de l'orchestre ?", answer: "Le violoncelle", points: 2 },
  { category: "arts", prompt: "Quel musée parisien abrite La Joconde ?", answer: "Le musée du Louvre", points: 2 },

  // ============ SPORT 🏆 (20 cards) — 2 points ============
  { category: "sport", prompt: "Quel pays a remporté la Coupe du Monde de football en 2018 ?", answer: "La France", points: 2 },
  { category: "sport", prompt: "Quel pays a remporté la Coupe du Monde de football en 2022 ?", answer: "L'Argentine", points: 2 },
  { category: "sport", prompt: "Combien de fois le Brésil a-t-il remporté la Coupe du Monde de football ?", answer: "Cinq fois", points: 2 },
  { category: "sport", prompt: "Dans quel pays se sont déroulés les Jeux Olympiques d'été de 2016 ?", answer: "Au Brésil", points: 2 },
  { category: "sport", prompt: "Combien de cercles composent les anneaux olympiques ?", answer: "Cinq", points: 2 },
  { category: "sport", prompt: "Quel pays a organisé les Jeux Olympiques d'été en 2024 ?", answer: "La France", points: 2 },
  { category: "sport", prompt: "Qui détient le record du monde du 100 mètres en athlétisme ?", answer: "Usain Bolt", points: 2 },
  { category: "sport", prompt: "Combien de joueurs composent une équipe de football sur le terrain ?", answer: "Onze", points: 2 },
  { category: "sport", prompt: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", answer: "Quinze", points: 2 },
  { category: "sport", prompt: "Quel tournoi de tennis annuel se joue sur gazon à Londres ?", answer: "Le tournoi de Wimbledon", points: 2 },
  { category: "sport", prompt: "Quel joueur de tennis suisse a remporté 20 tournois du Grand Chelem en simple ?", answer: "Roger Federer", points: 2 },
  { category: "sport", prompt: "Quel pays a remporté la Coupe du Monde de rugby en 2019 ?", answer: "L'Afrique du Sud", points: 2 },
  { category: "sport", prompt: "Quel cycliste belge surnommé le Cannibale a remporté le Tour de France à cinq reprises ?", answer: "Eddy Merckx", points: 2 },
  { category: "sport", prompt: "Dans quel sport pratique-t-on le slam dunk ?", answer: "Le basket-ball", points: 2 },
  { category: "sport", prompt: "Quel pilote de Formule 1 détient le record du plus grand nombre de victoires en Grand Prix ?", answer: "Lewis Hamilton", points: 2 },
  { category: "sport", prompt: "Quel pays a remporté la Coupe d'Afrique des Nations de football en 2024 ?", answer: "La Côte d'Ivoire", points: 2 },
  { category: "sport", prompt: "Quel boxeur américain surnommé The Greatest fut champion du monde des poids lourds ?", answer: "Muhammad Ali", points: 2 },
  { category: "sport", prompt: "Quel club de football a remporté la Ligue des champions le plus souvent ?", answer: "Le Real Madrid", points: 2 },
  { category: "sport", prompt: "Quel nageur américain a remporté 23 médailles d'or aux Jeux Olympiques ?", answer: "Michael Phelps", points: 2 },
  { category: "sport", prompt: "Dans quel stade se dispute chaque année la finale de la Coupe de France de football ?", answer: "Le Stade de France", points: 2 },

  // ============ JOKER 🎁 (20 cards) — 0 points (no answer) ============
  { category: "joker", prompt: "Double tes prochains points gagnés au prochain tour.", points: 0 },
  { category: "joker", prompt: "Donne 3 points à un autre joueur par générosité.", points: 0 },
  { category: "joker", prompt: "Rejoue immédiatement un tour (relance le dé).", points: 0 },
  { category: "joker", prompt: "Échange ton score avec un autre joueur.", points: 0 },
  { category: "joker", prompt: "Avance de 3 cases supplémentaires sans tirer de carte.", points: 0 },
  { category: "joker", prompt: "Reculle de 2 cases. La prochaine case s'applique.", points: 0 },
  { category: "joker", prompt: "Un autre joueur te donne 2 points de son score.", points: 0 },
  { category: "joker", prompt: "Tu repars de la case départ, mais +5 points de consolation.", points: 0 },
  { category: "joker", prompt: "Choisis la case de ton choix où atterrir (même côté du plateau).", points: 0 },
  { category: "joker", prompt: "Gagne 4 points bonus immédiatement.", points: 0 },
  { category: "joker", prompt: "Perds 3 points. La chance tourne !", points: 0 },
  { category: "joker", prompt: "Fais une pause et respire. Gagne 3 points de sérénité.", points: 0 },
  { category: "joker", prompt: "Inverse l'ordre du tour pour le prochain round.", points: 0 },
  { category: "joker", prompt: "Énonce ta prochaine stratégie à voix haute. +2 points.", points: 0 },
  { category: "joker", prompt: "Pioche une carte Histoire bonus immédiatement.", points: 0 },
  { category: "joker", prompt: "Choisis qui commence le prochain tour.", points: 0 },
  { category: "joker", prompt: "Gagne 1 point par joueur présent dans la partie (max 5).", points: 0 },
  { category: "joker", prompt: "Récite un proverbe célèbre. +3 points.", points: 0 },
  { category: "joker", prompt: "Tu es protégé de la prochaine pénalité.", points: 0 },
  { category: "joker", prompt: "Avance directement à la case Arts la plus proche.", points: 0 },
];

export const CARD_COUNTS: Record<CardCategory, number> = {
  histoire: 90,
  geographie: 60,
  sciences: 60,
  arts: 50,
  sport: 20,
  joker: 20,
};
